fastlane_version "2.192.0"  # Use the latest version

default_platform(:ios)

platform :ios do
  desc "Deploy to TestFlight"
  lane :beta do
    increment_build_number
    build_app(scheme: "Runner")  # Ensure the scheme is correct
    upload_to_testflight
  end
end
