-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgcdUCYuCVpnNqBUqT
3cjWhYdUL1Oa5z3Xos6ctLFByYugCgYIKoZIzj0DAQehRANCAATCQCRg/z4UZUxL
PojLX8m0htI5t8T5hldDQAu7lxNEwRxJX/9Dr7vos/ltKmqipZnwYxZwQ441Ne5r
TREnJaRL
-----END PRIVATE KEY-----