fastlane_version "2.225.0"

default_platform :ios

platform :ios do
  desc "Deploy to TestFlight"
  lane :beta do
    build_ios_app(
      scheme: "Runner",  # Replace this with your app's scheme
      export_method: "app-store"
    )
    upload_to_testflight
  end

  desc "Deploy to Production"
  lane :deploy do
    build_ios_app(
      scheme: "Runner",
      export_method: "app-store"
    )
    upload_to_app_store
  end
end
