name: iOS TestFlight Deployment

on:
  push:
    branches:
      - main  # Adjust if using a different branchs
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'  # Use your Flutter version

      - name: Install Fastlane
        run: |
          sudo gem install fastlane

      - name: Deploy to TestFlight
        run: |
          cd ios/fastlane  # Change to the directory containing the Fastfile
          fastlane ios deploy  # Call the deploy lane from the Fastfile
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APP_SPECIFIC_PASSWORD: ${{ secrets.APP_SPECIFIC_PASSWORD }}
          DEVELOPER_TEAM_ID: ${{ secrets.DEVELOPER_TEAM_ID }}
          BUNDLE_ID: ${{ secrets.BUNDLE_ID }}
